=begin
#Document AI API

#Use next-generation AI to extract data, fields, insights and text from documents. Instantly.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveDocumentaiApiClient::ExtractedTextPage
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExtractedTextPage' do
  before do
    # run before each test
    @instance = CloudmersiveDocumentaiApiClient::ExtractedTextPage.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExtractedTextPage' do
    it 'should create an instance of ExtractedTextPage' do
      expect(@instance).to be_instance_of(CloudmersiveDocumentaiApiClient::ExtractedTextPage)
    end
  end
  describe 'test attribute "page_number"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "text_result"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
