=begin
#Document AI API

#Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.

OpenAPI spec version: v1
Contact: support@cloudmersive.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveDocumentaiApiClient::PolicyRule
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PolicyRule' do
  before do
    # run before each test
    @instance = CloudmersiveDocumentaiApiClient::PolicyRule.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PolicyRule' do
    it 'should create an instance of PolicyRule' do
      expect(@instance).to be_instance_of(CloudmersiveDocumentaiApiClient::PolicyRule)
    end
  end
  describe 'test attribute "rule_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rule_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rule_description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
