=begin
#Document AI API

#Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.

OpenAPI spec version: v1
Contact: support@cloudmersive.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module CloudmersiveDocumentaiApiClient
  # Request to perform an AI field extraction on a document
  class AdvancedExtractFieldsRequest
    # Input document file to perform the operation on as a byte array
    attr_accessor :input_file

    # Fields to extract from the document
    attr_accessor :fields_to_extract

    # Optional: Limit the number of pages processed
    attr_accessor :maximum_pages_processed

    # Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are 'Auto', 'SmoothEdges', 'SmoothEdgesPlus', 'ContrastEdges', 'ContrastEdgesPlus', 'Invert', 'Binarize', 'Compatability' and 'None'.  Default is Auto.  Set to SmoothEdges to smooth harsh edges in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree.  Set to ContrastEdges and ContrastEdgesPlus to enhance contrast and readability for low quality black and white or grayscale images.  Set to Invert to invert the input image.  Set to Binarize to binarize the input image.  Set to Compatability for maximum PDF feature compatability.
    attr_accessor :preprocessing

    # Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are 'None', 'Advanced' and 'Ultra'.  Default is None.  Ultra will produce the highest accuracy but at the cost of longer processing times.
    attr_accessor :result_cross_check

    # Optional: Rotate the input image before recognition by the specified number of degrees; valid values range from -360 to +360.
    attr_accessor :rotate_image_degrees

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'input_file' => :'InputFile',
        :'fields_to_extract' => :'FieldsToExtract',
        :'maximum_pages_processed' => :'MaximumPagesProcessed',
        :'preprocessing' => :'Preprocessing',
        :'result_cross_check' => :'ResultCrossCheck',
        :'rotate_image_degrees' => :'RotateImageDegrees'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'input_file' => :'String',
        :'fields_to_extract' => :'Array<FieldToExtract>',
        :'maximum_pages_processed' => :'Integer',
        :'preprocessing' => :'String',
        :'result_cross_check' => :'String',
        :'rotate_image_degrees' => :'Float'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'InputFile')
        self.input_file = attributes[:'InputFile']
      end

      if attributes.has_key?(:'FieldsToExtract')
        if (value = attributes[:'FieldsToExtract']).is_a?(Array)
          self.fields_to_extract = value
        end
      end

      if attributes.has_key?(:'MaximumPagesProcessed')
        self.maximum_pages_processed = attributes[:'MaximumPagesProcessed']
      end

      if attributes.has_key?(:'Preprocessing')
        self.preprocessing = attributes[:'Preprocessing']
      end

      if attributes.has_key?(:'ResultCrossCheck')
        self.result_cross_check = attributes[:'ResultCrossCheck']
      end

      if attributes.has_key?(:'RotateImageDegrees')
        self.rotate_image_degrees = attributes[:'RotateImageDegrees']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@input_file.nil? && @input_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        invalid_properties.push('invalid value for "input_file", must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@input_file.nil? && @input_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] input_file Value to be assigned
    def input_file=(input_file)
      if !input_file.nil? && input_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        fail ArgumentError, 'invalid value for "input_file", must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.'
      end

      @input_file = input_file
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          input_file == o.input_file &&
          fields_to_extract == o.fields_to_extract &&
          maximum_pages_processed == o.maximum_pages_processed &&
          preprocessing == o.preprocessing &&
          result_cross_check == o.result_cross_check &&
          rotate_image_degrees == o.rotate_image_degrees
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [input_file, fields_to_extract, maximum_pages_processed, preprocessing, result_cross_check, rotate_image_degrees].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CloudmersiveDocumentaiApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
