=begin
#Document AI API

#Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.

OpenAPI spec version: v1
Contact: support@cloudmersive.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDocumentaiApiClient::AnalyzeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AnalyzeApi' do
  before do
    # run before each test
    @instance = CloudmersiveDocumentaiApiClient::AnalyzeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyzeApi' do
    it 'should create an instance of AnalyzeApi' do
      expect(@instance).to be_instance_of(CloudmersiveDocumentaiApiClient::AnalyzeApi)
    end
  end

  # unit tests for answer_questions
  # Answer Questions about a Document in a structured way using Advanced AI
  # Answer boolean (yes/no), multiple-choice and free-response questions about the contents of a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Consumes 100 API calls per page.
  # @param [Hash] opts the optional parameters
  # @option opts [DocumentQuestionsRequest] :body Input request, including document and questions
  # @return [DocumentQuestionAnswersResult]
  describe 'answer_questions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apply_rules
  # Enforce Policies to a Document to allow or block it using Advanced AI
  # Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Consumes 100 API calls per page.
  # @param [Hash] opts the optional parameters
  # @option opts [DocumentPolicyRequest] :body Input request, including document and policy rules
  # @return [DocumentPolicyResult]
  describe 'apply_rules test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
