=begin
#Document AI API

#Use next-generation AI to extract data, fields, insights and text from documents. Instantly.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDocumentaiApiClient::AnalyzeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AnalyzeApi' do
  before do
    # run before each test
    @instance = CloudmersiveDocumentaiApiClient::AnalyzeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyzeApi' do
    it 'should create an instance of AnalyzeApi' do
      expect(@instance).to be_instance_of(CloudmersiveDocumentaiApiClient::AnalyzeApi)
    end
  end

  # unit tests for apply_rules
  # Enforce Policies to a Document to allow or block it using Advanced AI
  # Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [DocumentPolicyRequest] :body Input request, including document and policy rules
  # @return [DocumentPolicyResult]
  describe 'apply_rules test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
