=begin
#Document AI API

#Use next-generation AI to extract data, fields, insights and text from documents. Instantly.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDocumentaiApiClient::ExtractApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExtractApi' do
  before do
    # run before each test
    @instance = CloudmersiveDocumentaiApiClient::ExtractApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExtractApi' do
    it 'should create an instance of ExtractApi' do
      expect(@instance).to be_instance_of(CloudmersiveDocumentaiApiClient::ExtractApi)
    end
  end

  # unit tests for extract_all_fields_and_tables
  # Extract All Fields and Tables of Data from a Document using AI
  # Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractFieldsAndTablesResponse]
  describe 'extract_all_fields_and_tables test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_barcodes
  # Extract Barcodes of from a Document using AI
  # Extract all barcodes from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractBarcodesAiResponse]
  describe 'extract_barcodes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_classification
  # Extract Classification or Category from a Document using AI
  # Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :categories Desired classification to extract
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [DocumentClassificationResult]
  describe 'extract_classification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_classification_advanced
  # Extract Classification or Category from a Document using Advanced AI
  # Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [AdvancedExtractClassificationRequest] :body Input request to perform the classification on
  # @return [DocumentAdvancedClassificationResult]
  describe 'extract_classification_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_fields
  # Extract Field Values from a Document using AI
  # Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :field_names Desired fields to extract, comma separated
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractFieldsResponse]
  describe 'extract_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_fields_advanced
  # Extract Field Values from a Document using Advanced AI
  # Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [AdvancedExtractFieldsRequest] :body Input request, including document file as byte array, and information on which fields to extract
  # @return [ExtractFieldsResponse]
  describe 'extract_fields_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_summary
  # Extract Summary from a Document using AI
  # Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [SummarizeDocumentResponse]
  describe 'extract_summary test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_tables
  # Extract Tables of Data from a Document using AI
  # Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractTablesResponse]
  describe 'extract_tables test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_text
  # Extract Text from a Document using AI
  # Extract raw text from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractTextResponse]
  describe 'extract_text test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
