=begin
#Document AI API

#Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.

OpenAPI spec version: v1
Contact: support@cloudmersive.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDocumentaiApiClient::RunBatchJobApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RunBatchJobApi' do
  before do
    # run before each test
    @instance = CloudmersiveDocumentaiApiClient::RunBatchJobApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RunBatchJobApi' do
    it 'should create an instance of RunBatchJobApi' do
      expect(@instance).to be_instance_of(CloudmersiveDocumentaiApiClient::RunBatchJobApi)
    end
  end

  # unit tests for extract_all_fields_and_tables_from_document_batch_job
  # Extract All Fields and Tables of Data from a Document using AI as a Batch Job
  # Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractDocumentBatchJobResult]
  describe 'extract_all_fields_and_tables_from_document_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_classification_from_document_batch_job
  # Extract Classification or Category from a Document using AI as a Batch Job
  # Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :categories Desired classification to extract
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractDocumentBatchJobResult]
  describe 'extract_classification_from_document_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_fields_from_document_advanced_batch_job
  # Extract Field Values from a Document using Advanced AI as a Batch Job
  # Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [AdvancedExtractFieldsRequest] :body Input document and parameters
  # @return [ExtractDocumentBatchJobResult]
  describe 'extract_fields_from_document_advanced_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extract_text_from_document_batch_job
  # Extract Text from a Document using AI as a Batch Job
  # Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :recognition_mode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [ExtractDocumentBatchJobResult]
  describe 'extract_text_from_document_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_async_job_status
  # Get the status and result of an Extract Document Batch Job
  # Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :async_job_id Job ID for the batch job to get the status of
  # @return [ExtractDocumentJobStatusResult]
  describe 'get_async_job_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
