=begin
#Document AI API

#Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.

OpenAPI spec version: v1
Contact: support@cloudmersive.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-documentai-api-client/api_client'
require 'cloudmersive-documentai-api-client/api_error'
require 'cloudmersive-documentai-api-client/version'
require 'cloudmersive-documentai-api-client/configuration'

# Models
require 'cloudmersive-documentai-api-client/models/advanced_extract_classification_request'
require 'cloudmersive-documentai-api-client/models/advanced_extract_fields_request'
require 'cloudmersive-documentai-api-client/models/document_advanced_classification_result'
require 'cloudmersive-documentai-api-client/models/document_categories'
require 'cloudmersive-documentai-api-client/models/document_classification_result'
require 'cloudmersive-documentai-api-client/models/document_policy_request'
require 'cloudmersive-documentai-api-client/models/document_policy_result'
require 'cloudmersive-documentai-api-client/models/document_question_answer_item'
require 'cloudmersive-documentai-api-client/models/document_question_answers_result'
require 'cloudmersive-documentai-api-client/models/document_question_boolean'
require 'cloudmersive-documentai-api-client/models/document_question_choice_item'
require 'cloudmersive-documentai-api-client/models/document_question_free_response'
require 'cloudmersive-documentai-api-client/models/document_question_multiple_choice'
require 'cloudmersive-documentai-api-client/models/document_questions_request'
require 'cloudmersive-documentai-api-client/models/extract_barcodes_ai_response'
require 'cloudmersive-documentai-api-client/models/extract_document_batch_job_result'
require 'cloudmersive-documentai-api-client/models/extract_document_job_status_result'
require 'cloudmersive-documentai-api-client/models/extract_fields_advanced_response'
require 'cloudmersive-documentai-api-client/models/extract_fields_and_tables_response'
require 'cloudmersive-documentai-api-client/models/extract_fields_response'
require 'cloudmersive-documentai-api-client/models/extract_tables_response'
require 'cloudmersive-documentai-api-client/models/extract_text_response'
require 'cloudmersive-documentai-api-client/models/extracted_barcode_item'
require 'cloudmersive-documentai-api-client/models/extracted_text_page'
require 'cloudmersive-documentai-api-client/models/field_advanced_value'
require 'cloudmersive-documentai-api-client/models/field_to_extract'
require 'cloudmersive-documentai-api-client/models/field_value'
require 'cloudmersive-documentai-api-client/models/policy_rule'
require 'cloudmersive-documentai-api-client/models/policy_rule_violation'
require 'cloudmersive-documentai-api-client/models/split_document_response'
require 'cloudmersive-documentai-api-client/models/sub_document'
require 'cloudmersive-documentai-api-client/models/summarize_document_response'
require 'cloudmersive-documentai-api-client/models/table_result'
require 'cloudmersive-documentai-api-client/models/table_result_cell'
require 'cloudmersive-documentai-api-client/models/table_result_row'

# APIs
require 'cloudmersive-documentai-api-client/api/analyze_api'
require 'cloudmersive-documentai-api-client/api/extract_api'
require 'cloudmersive-documentai-api-client/api/run_batch_job_api'

module CloudmersiveDocumentaiApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveDocumentaiApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
